version: '3.1'

services:

  doctors-db:
    image: postgres-doctors-db
    restart: always
    ports:
      - "5432:5432"
      
  clinics-db:
    image: mysql-clinics-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always